import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Provider from "@/context/Provider";
import { GoogleOAuthProvider } from "@react-oauth/google";

export const metadata: Metadata = {
  title: "Instkram",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="shortcut icon"
        href="https://cdn-icons-png.flaticon.com/512/2065/2065157.png"
        type="image/x-icon"
      />
      <body>
        <main>
          <div className="h-lvh mx-auto p-6">
            <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID}>
              <Provider>
                <Header />

                {children}
              </Provider>
            </GoogleOAuthProvider>
          </div>
        </main>
      </body>
    </html>
  );
}
